# Generated by Django 5.1.2 on 2024-11-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrevistas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
