# Generated by Django 5.1.2 on 2024-12-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrevistas', '0002_question_audio_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='classificacao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
