# Generated by Django 5.1.2 on 2025-03-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrevistas', '0003_interview_classificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='empresa',
            field=models.CharField(default='Vodacom', max_length=255),
            preserve_default=False,
        ),
    ]
