# Generated by Django 5.1.2 on 2025-01-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions_personalidade', '0002_test_answerpersonalidade_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerpersonalidade',
            old_name='test',
            new_name='test_id',
        ),
    ]
