# Generated by Django 5.1.2 on 2025-01-12 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions_personalidade', '0003_rename_test_answerpersonalidade_test_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerpersonalidade',
            old_name='test_id',
            new_name='test',
        ),
    ]
