# Generated by Django 5.1.2 on 2025-01-12 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_personalidade', '0004_rename_test_id_answerpersonalidade_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerpersonalidade',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions_personalidade.test'),
        ),
    ]
