# Generated by Django 5.1.2 on 2025-04-12 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_personalidade', '0005_alter_answerpersonalidade_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extroversao', models.IntegerField()),
                ('amabilidade', models.IntegerField()),
                ('consciencia', models.IntegerField()),
                ('neuroticismo', models.IntegerField()),
                ('abertura_experiencia', models.IntegerField()),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personality_score', to='questions_personalidade.test')),
            ],
        ),
    ]
