# Generated by Django 5.1.2 on 2025-04-13 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions_personalidade', '0007_remove_test_user_id_test_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='user',
            new_name='users',
        ),
    ]
