# Generated by Django 5.1.2 on 2025-04-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_personalidade', '0008_rename_user_test_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='users',
        ),
        migrations.AddField(
            model_name='test',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
