# Generated by Django 5.1.2 on 2025-04-13 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_personalidade', '0009_remove_test_users_test_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='user_id',
        ),
        migrations.AddField(
            model_name='test',
            name='user',
            field=models.ForeignKey(default='45997356-6d32-486a-9f70-2abe6dc7d184', on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
