# Generated by Django 5.1.2 on 2025-04-13 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_personalidade', '0010_remove_test_user_id_test_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerpersonalidade',
            name='user_id',
        ),
        migrations.AddField(
            model_name='answerpersonalidade',
            name='user',
            field=models.ForeignKey(default='45997356-6d32-486a-9f70-2abe6dc7d184', on_delete=django.db.models.deletion.CASCADE, related_name='personalidade_answers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answerpersonalidade',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions_personalidade.questionpersonalidade'),
        ),
        migrations.AlterField(
            model_name='answerpersonalidade',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalidade_answers', to='questions_personalidade.test'),
        ),
    ]
