# Generated by Django 5.1.2 on 2025-02-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier_guide', '0002_question_correct_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='metadata',
            new_name='chart_data',
        ),
        migrations.AddField(
            model_name='question',
            name='chart_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
