# Generated by Django 5.1.2 on 2025-02-08 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrier_guide', '0003_rename_metadata_question_chart_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='chart_data',
            new_name='metadata',
        ),
        migrations.RemoveField(
            model_name='question',
            name='chart_url',
        ),
        migrations.RemoveField(
            model_name='question',
            name='code',
        ),
    ]
