# Generated by Django 5.1.2 on 2025-04-10 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier_guide', '0004_rename_chart_data_question_metadata_and_more'),
        ('questions_personalidade', '0005_alter_answerpersonalidade_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='cognitivetest',
            name='id_teste_personalidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cognitive_tests', to='questions_personalidade.test'),
            preserve_default=False,
        ),
    ]
