# Generated by Django 5.1.2 on 2025-04-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier_guide', '0005_cognitivetest_id_teste_personalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cognitivetest',
            name='cargo_atual',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cognitivetest',
            name='cargo_desejado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
