# Generated by Django 5.1.2 on 2025-01-14 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='summary',
        ),
    ]
