# Generated by Django 5.1.2 on 2025-01-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_remove_personalinfo_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executableproject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
