# Generated by Django 5.1.2 on 2025-01-21 10:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_alter_executableproject_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTransacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='cv',
            name='awards',
            field=models.ManyToManyField(related_name='cvs', to='curriculum.award'),
        ),
        migrations.AddField(
            model_name='cv',
            name='educations',
            field=models.ManyToManyField(related_name='cvs', to='curriculum.education'),
        ),
        migrations.AddField(
            model_name='cv',
            name='experiences',
            field=models.ManyToManyField(related_name='cvs', to='curriculum.experience'),
        ),
        migrations.AddField(
            model_name='cv',
            name='internships',
            field=models.ManyToManyField(related_name='cvs', to='curriculum.internship'),
        ),
        migrations.AddField(
            model_name='cv',
            name='languages',
            field=models.ManyToManyField(related_name='cvs', to='curriculum.language'),
        ),
        migrations.AddField(
            model_name='cv',
            name='projects',
            field=models.ManyToManyField(related_name='cvs', to='curriculum.executableproject'),
        ),
        migrations.AddField(
            model_name='cv',
            name='references',
            field=models.ManyToManyField(related_name='cvs', to='curriculum.referenc'),
        ),
        migrations.AddField(
            model_name='cv',
            name='short_educations',
            field=models.ManyToManyField(related_name='cvs', to='curriculum.shorteducation'),
        ),
        migrations.AddField(
            model_name='cv',
            name='skills',
            field=models.ManyToManyField(related_name='cvs', to='curriculum.skill'),
        ),
        migrations.AddField(
            model_name='cv',
            name='softwares',
            field=models.ManyToManyField(related_name='cvs', to='curriculum.software'),
        ),
        migrations.AddField(
            model_name='cv',
            name='volunteer_work',
            field=models.ManyToManyField(related_name='cvs', to='curriculum.volunteer'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='credito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='Ativo', max_length=20),
        ),
        migrations.CreateModel(
            name='TipoUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('users', models.ManyToManyField(blank=True, related_name='tipos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.tipotransacao')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
