# Generated by Django 5.1.2 on 2025-02-23 09:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_tipotransacao_cv_awards_cv_educations_cv_experiences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credito',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('metodoPagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.tipotransacao')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
