# Generated by Django 5.1.2 on 2025-03-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0014_educationjd_experiencejd_languagejd_softwarejd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencejd',
            name='year_of_experience',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
