# Generated by Django 5.1.2 on 2025-03-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0016_alter_skill_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='language_cv',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
