# Generated by Django 5.1.2 on 2025-03-23 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0017_cv_language_cv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='metodoPagamento',
            new_name='metodo_pagamento',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='data',
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='data',
        ),
        migrations.AddField(
            model_name='transacao',
            name='credit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacao', to='curriculum.credit'),
        ),
        migrations.AddField(
            model_name='transacao',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
