# Generated by Django 5.1.2 on 2025-03-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0018_rename_metodopagamento_credit_metodo_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='metodo_pagamento',
            field=models.CharField(max_length=100),
        ),
    ]
