# Generated by Django 5.1.2 on 2025-04-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0019_alter_credit_metodo_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='valid_until',
            field=models.DateTimeField(null=True),
        ),
    ]
