# Generated by Django 5.1.2 on 2025-04-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0021_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='salary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
