# Generated by Django 5.1.2 on 2025-04-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0022_experience_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
