# Generated by Django 5.1.2 on 2025-04-13 17:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0024_alter_skill_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='executableproject',
            name='associated_title',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
