# Generated by Django 5.1.2 on 2025-04-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0025_executableproject_associated_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='valor_convertido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
