# Generated by Django 5.1.2 on 2025-05-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0028_populate_tipotransacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
    ]
