# Generated by Django 5.1.2 on 2025-05-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0029_personalinfo_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='educationjd',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
