# Generated by Django 5.1.2 on 2025-06-11 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0030_alter_education_field_of_study_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='cv',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to='curriculum.cv'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
