# Generated by Django 5.1.2 on 2025-06-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0031_remove_personalinfo_user_personalinfo_cv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
