# Generated by Django 5.1.2 on 2025-07-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0032_personalinfo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationjd',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
