# Generated by Django 5.1.2 on 2026-05-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0033_educationjd_degree"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalinfo",
            name="phone",
            field=models.CharField(max_length=50),
        ),
    ]
